Title
========================================================


```{r}
setwd("/mnt/hgfs//WorkSpaces//Bicycle")
## 读取源数据
if(F){
  path <- c("/mnt/hgfs//WorkSpaces//Bicycle//data//")
  files <- dir(path)
  records<-NULL
  for(i in files){  
    wj<-paste(path,i,sep="")
    print(wj)
    temp <- read.xlsx2(wj,sheetIndex=1, header = TRUE)
    records<-rbind(records,temp)
  }
  save(records,file ='data/records.RData')
  write.csv(records,file="data/records.csv")
}
## 数据分析
dim(records)
head(records)
summary(records)

## 分别统计各站点20天中每天及累计的借车频次和还车频次,并对所有站点按累计的借车频次和还车频次分别给出它们的排序

###借车
##共有184个车站

jiechuTotal <- table(records$借出车站)
barplot(jiechuTotal)
aggregate(x=records,by = list("借出车站"), FUN=length )



guihuanTotal <-table(records$归还车站)
barplot(guihuanTotal)


nlevels(records$借出车站)





## 试统计分析每次用车时长的分布情况
records$用车时间 <- as.numeric(records$用车时间)
summary(records$用车时间)
hist(records$用车时间)
boxplot(records$用车时间)


## 试统计20天中各天使用公共自行车的不同借车卡（即借车人）数量，并统计数据中出现过的每张借车卡累计借车次数的分布情况。

aa <- table(records$No.,as.Date(records$借车时刻))
dim(aa)

barplot(table(records$No.))

table(as.Date(records$借车时刻))





ind <- list(c(1, 2, 2), c("A", "A", "B"))
table(ind)
tapply(1:3, ind) #-> the split vector
tapply(1:3, ind, sum)


table(records$借出车站)

install.packages("xlsx")




library(xlsx)
records1 <- read.xlsx2("/mnt//hgfs//WorkSpaces//Bicycle//data//第1天.xls",sheetIndex=1, header = TRUE)

for( i in c(1:2)){
  temp <-  read.xlsx2("/mnt//hgfs//WorkSpaces//Bicycle//data//第$i天.xls",sheetIndex=1, header = TRUE)
  head(temp)
}


dim(records1)
head(records1)

```

You can also embed plots, for example:

```{r fig.width=7, fig.height=6}
plot(cars)
```

